@h1 = Example Domain
@baseUrl = http://example.com

# @name getExample
GET {{baseUrl}} HTTP/1.1

>>>

assert {{response.status_code}} == 200
assert 'text/html' in {{response.headers.content-type}}
assert {{h1}} in {{response.body}}

###

@exampleBody = {{getExample.response.body}}

# @name getExampleNotFound
GET {{baseUrl}}/abc HTTP/1.1

>>>

assert {{response.status_code}} == 404
assert {{exampleBody}} == {{response.body}}

###

# @name postExample
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{}

>>>

assert {{response.status_code}} == 200
assert {{response.doesNotExists}} is None
assert {{invalid}} is None
