name: deploy-package
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install .
      - name: run tests
        run: |
          . venv/bin/activate
          testhttp --pattern 'tests/*.http'
      - name: build distributable
        run: python3 setup.py sdist bdist_wheel
      - name: publish
        run: |
          python3 -m pip install --user --upgrade twine
          python3 -m twine upload -u '__token__' -p '${{ secrets.API_TOKEN }}' dist/*
